version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Use Amazon Corretto 11 for the Java runtime
    commands:
      - echo Installing dependencies...
      # - sudo yum update -y
      - sudo yum install -y httpd
      # - sudo amazon-linux-extras install java-openjdk11 -y
      - mvn install -DskipTests # Install dependencies, skipping tests for faster builds
  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package # Clean and package the Spring Boot application
      - cd src/web/app
      - echo Running mvn jetty:run in src/web/app directory --auto-approve
      - mvn jetty:run -Dspring-boot.run.jvmArguments="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'target/*'
    - 'buildspec/'
  discard-paths: yes 

# cache:
#   paths:
#     - '/root/.m2/**/*' 
